server:
  port: 80

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8888/eureka

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: sample-service
          uri: lb://SAMPLE-SERVICE
          predicates:
            - Path=/api/sample